### ISSUE TITLE
Log Levels: feedback incorrectly recommends to use the substring method

### ISSUE THREAD

**Issue by santhoshswamyv** [exercism/java-analyzer#150]
# Issue in Log Levels Exercise

I used the substring method to solve the exercise but the automated feedback insists me to use substring. Resolve this issue as soon as possible.

![image](https://github.com/exercism/java-analyzer/assets/138140952/9886115d-b4d4-4cd6-9afb-e97709b9779b)

```bash
class LogLevels {

	public static String message(String logLine) {
		logLine = logLine.substring(logLine.indexOf(":") + 1);
		return logLine.trim();
	}

	public static String logLevel(String logLine) {
		if (logLine.toLowerCase().contains("info"))
			return "info";
		if (logLine.toLowerCase().contains("warning"))
			return "warning";

		return "error";
	}

	public static String reformat(String logLine) {
		return message(logLine) + " (" + logLevel(logLine) + ")";
	}
}
```
```

**Comment by sanderploegsma** [comment]
Thanks for your feedback! This seems like an interesting bug in the analyzer, we'll look into it.

Could you please add a comment to this issue with your solution code as text instead of as a screenshot?
This makes it easier for our contributing team to work on this issue, as they can use it to test whether the bug has been solved.
And to make it readable, I'd suggest using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) when you do.

> Resolve this issue as soon as possible.

Please be mindful in the way you communicate to others. You may not have intended it this way, but the tone of this comment is _very_ demanding and could even be considered as disrespectful to the Exercism contributors, who build this platform as volunteers and in their spare time.

**Comment by santhoshswamyv** [comment]
> Thanks for your feedback! This seems like an interesting bug in the analyzer, we'll look into it.
> 
> Could you please add a comment to this issue with your solution code as text instead of as a screenshot? This makes it easier for our contributing team to work on this issue, as they can use it to test whether the bug has been solved. And to make it readable, I'd suggest using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) when you do.
> 
> > Resolve this issue as soon as possible.
> 
> Please be mindful in the way you communicate to others. You may not have intended it this way, but the tone of this comment is _very_ demanding and could even be considered as disrespectful to the Exercism contributors, who build this platform as volunteers and in their spare time.

> I’m sorry if my previous message came across as demanding or disrespectful. That was not my intention. I appreciate the hard work you all put into this platform. Thank you for your understanding.

**Comment by MrXcitement** [comment]
I am also receiving the feedback of 'Recommended: Consider using the substring method to solve this exercise.' when submitting my solutions. I am using `substring` in the logLevel method, to return the text between left and right square braces. Could this be due to the fact in the `messages` methode, I am not using substring, but split?

My last submitted solution:
```java
public class LogLevels {

    public static String message(String logLine) {
        return logLine.split(": ", 2)[1]
        .trim();
    }

    public static String logLevel(String logLine) {
        return logLine
        .substring(logLine.indexOf('[') + 1, logLine.indexOf(']'))
        .toLowerCase();
    }

    public static String reformat(String logLine) {
        return message(logLine) + " (" + logLevel(logLine) + ")";
    }
}
```

**Comment by sanderploegsma** [comment]
@MrXcitement thanks for your feedback! I think you're right, you're receiving the analyzer feedback because the `message` method doesn't use `substring`.

@manumafe98 any particular reason why the analyzer should instruct students to choose `substring` over `split`? IMO the solution above is great and doesn't need further improvements, but perhaps you have a different opinion. If not, perhaps we should revisit the analyzer implementation to narrow down the cases where it suggests to use `substring`.

**Comment by manumafe98** [comment]
> @manumafe98 any particular reason why the analyzer should instruct students to choose `substring` over `split`? IMO the solution above is great and doesn't need further improvements, but perhaps you have a different opinion. If not, perhaps we should revisit the analyzer implementation to narrow down the cases where it suggests to use `substring`.

Well in the concept exercise we were guiding students to the [exemplar](https://github.com/exercism/java/blob/main/exercises/concept/log-levels/.meta/src/reference/java/LogLevels.java) solution right? And also we defined this comment on the [design.md](https://github.com/exercism/java/blob/f6b855e081b905def0f56a267498e7ed2d7e6789/exercises/concept/log-levels/.meta/design.md?plain=1#L32)

Maybe we could also allow the usage of split in the `message` method

**Comment by sanderploegsma** [comment]
Yes, that is indeed the point. However, I'd argue that sometimes a solution can be equivalent to the exemplar solution without being the same. 😉

In fact, given that this exercise teaches the `strings` concept, I like the solution shared by @MrXcitement since it applies the concept in multiple ways using both `split` and `substring` 👍
